version: '2.1'

services:
  db:
    ports:
      - 5432:5432
    image: postgres:14.1-alpine
    container_name: swapi_postgres
    volumes:
      - .data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 2s
      timeout: 3s
      retries: 40
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: swapi
    container_name: swapi_app
    depends_on:
      db:
        condition: service_healthy
